
set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR arm)

set(TARGET_TRIPLET arm-none-eabi)

set(CMAKE_ASM_COMPILER ${TARGET_TRIPLET}-gcc)
set(CMAKE_ASM_COMPILER_TARGET ${TARGET_TRIPLET})
set(CMAKE_ASM_FLAGS_DEBUG "-O0 -ggdb")
set(CMAKE_ASM_FLAGS_MINSIZEREL "-Os -DNDEBUG")
set(CMAKE_ASM_FLAGS_RELEASE "-O3 -DNDEBUG")
set(CMAKE_ASM_FLAGS_RELWITHDEBINFO "-O2 -ggdb -DNDEBUG")

set(CMAKE_C_COMPILER ${TARGET_TRIPLET}-gcc)
set(CMAKE_C_COMPILER_TARGET ${TARGET_TRIPLET})
set(CMAKE_C_STANDARD 11)
set(CMAKE_C_EXTENSIONS ON)
set(CMAKE_C_FLAGS_DEBUG "-O0 -ggdb")
set(CMAKE_C_FLAGS_MINSIZEREL "-Os -DNDEBUG")
set(CMAKE_C_FLAGS_RELEASE "-O3 -DNDEBUG")
set(CMAKE_C_FLAGS_RELWITHDEBINFO "-O2 -ggdb -DNDEBUG")

set(CMAKE_CXX_COMPILER ${TARGET_TRIPLET}-g++)
set(CMAKE_CXX_COMPILER_TARGET ${TARGET_TRIPLET})
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS ON)
set(CMAKE_CXX_FLAGS_DEBUG "-O0 -ggdb")
set(CMAKE_CXX_FLAGS_MINSIZEREL "-Os -DNDEBUG")
set(CMAKE_CXX_FLAGS_RELEASE "-O3 -DNDEBUG")
set(CMAKE_CXX_FLAGS_RELWITHDEBINFO "-O2 -ggdb -DNDEBUG")

set(TARGET_OBJCOPY ${TARGET_TRIPLET}-objcopy)
set(TARGET_SIZE ${TARGET_TRIPLET}-size)

# Don't run the linker on compiler check
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

set(CMAKE_ASM_FLAGS "${CMAKE_C_FLAGS} -mcpu=cortex-m3 -mthumb -ffreestanding -nostdinc -Wall -Werror")
set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -mcpu=cortex-m3 -mthumb -ffreestanding -nostdinc -Wall -Werror")
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -mcpu=cortex-m3 -mthumb -ffreestanding -nostdinc -Wall -Werror")
set(CMAKE_EXE_LINKER_FLAGS "-T ${CMAKE_CURRENT_SOURCE_DIR}/system/flash.ld -Wl,--entry=reset_handler -Wl,--gc-sections")
